In [51]:
import pandas as pd

# Read the Excel file without treating the first row as headers
df = pd.read_excel(r'C:\Users\Ali Muhtasham Javed\Downloads\indian_startup_funding_Lab1.xlsx')
#df.loc[0:112].. can be used to get data in tabular form.. 
df

,Stock,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Sr No,Date,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
1,17,2019-12-20 00:00:00,Lenskart.com,E-Commerce,Online Eyewear Shopping Portal,Faridabad,SoftBank Vision Fund,Series G,231000000,NaN
2,12,2019-12-17 00:00:00,Healthians,B2B-focused foodtech startup,Food Solutions For Corporate,Bengaluru,"Paytm, NPTK, Sabre Partners and Neoplux",Series C,12000000,NaN
3,13,2019-12-16 00:00:00,Licious,E-Commerce,Online Meat And Seafood Ordering Startup,Bengaluru,Vertex Growth Fund,Series E,30000000,NaN
4,14,2019-12-16 00:00:00,InCred,Finance,Non-Banking Financial Company,Mumbai,NaN,Debt Funding,5900000,NaN
...,...,...,...,...,...,...,...,...,...,...
107,114,2019-02-08 00:00:00,Zilingo,Ecommerce,Fashion & Apparel,India/Singapore,"Sequoia Capital and Temasek Holdings, EDBI, Bu...",Series D,226000000,NaN
108,113,2019-02-01 00:00:00,FleetX,AI,Logistics,Gurgaon,India Quotient and LetsVenture\\xe2\\x80\\x99s...,Pre Series A,Undisclosed,NaN
109,118,2019-01-04 00:00:00,Vyome Therapeutics Inc.,Health and Wellness,Specialty pharmaceutical,India/US,"Iron Pillar, Perceptive Advisors, Romulus Capi...",Series D,22000000,NaN
110,119,2019-01-04 00:00:00,Samunnati Financial Intermediation & Services ...,Finance,Non-banking financial company,Chennai,"MASSIF, a Dutch government fund",Debt-Funding,5000000,NaN
111,117,2019-01-03 00:00:00,CarDekho,Automobile,Online Marketplace,Jaipur,"Sequoia India, Hillhouse Capital, Alphabet\\xe...",Series C,110000000,NaN

In [52]:
import pandas as pd

# Read the Excel file without treating the first row as headers
df = pd.read_excel(r'C:\Users\Ali Muhtasham Javed\Downloads\indian_startup_funding_Lab1.xlsx',header = 1)
df


#if there are no column names following code can help in naming the column names .
#df = pd.read_excel(r'C:\Users\Ali Muhtasham Javed\Downloads\indian_startup_funding_Lab1.xlsx',header = 1, names = ['A','B','C'])

,Sr No,Date,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,17,2019-12-20,Lenskart.com,E-Commerce,Online Eyewear Shopping Portal,Faridabad,SoftBank Vision Fund,Series G,231000000,NaN
1,12,2019-12-17,Healthians,B2B-focused foodtech startup,Food Solutions For Corporate,Bengaluru,"Paytm, NPTK, Sabre Partners and Neoplux",Series C,12000000,NaN
2,13,2019-12-16,Licious,E-Commerce,Online Meat And Seafood Ordering Startup,Bengaluru,Vertex Growth Fund,Series E,30000000,NaN
3,14,2019-12-16,InCred,Finance,Non-Banking Financial Company,Mumbai,NaN,Debt Funding,5900000,NaN
4,15,2019-12-14,Trell,Video,Experience Discovery Platform,Bengaluru,Ruizheng Investment,Seed Round,2000000,NaN
...,...,...,...,...,...,...,...,...,...,...
106,114,2019-02-08,Zilingo,Ecommerce,Fashion & Apparel,India/Singapore,"Sequoia Capital and Temasek Holdings, EDBI, Bu...",Series D,226000000,NaN
107,113,2019-02-01,FleetX,AI,Logistics,Gurgaon,India Quotient and LetsVenture\\xe2\\x80\\x99s...,Pre Series A,Undisclosed,NaN
108,118,2019-01-04,Vyome Therapeutics Inc.,Health and Wellness,Specialty pharmaceutical,India/US,"Iron Pillar, Perceptive Advisors, Romulus Capi...",Series D,22000000,NaN
109,119,2019-01-04,Samunnati Financial Intermediation & Services ...,Finance,Non-banking financial company,Chennai,"MASSIF, a Dutch government fund",Debt-Funding,5000000,NaN
110,117,2019-01-03,CarDekho,Automobile,Online Marketplace,Jaipur,"Sequoia India, Hillhouse Capital, Alphabet\\xe...",Series C,110000000,NaN

In [53]:
df = df.sort_values(by= 'Sr No', ascending=True)
df
#indexing ruined.

,Sr No,Date,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
6,8,2019-12-12,Ecozen,Technology,Agritech,Pune,Sathguru Catalyzer Advisors,Series A,6000000,NaN
8,9,2019-12-06,CarDekho,E-Commerce,Automobile,Gurgaon,Ping An Global Voyager Fund,Series D,70000000,NaN
9,10,2019-12-03,Dhruva Space,Aerospace,Satellite Communication,Bengaluru,"Mumbai Angels, Ravikanth Reddy",Seed,50000000,NaN
5,11,2019-12-13,Rivigo,Technology,Logistics Services and Solutions,Gurgaon,"SAIF Partners, Spring Canter Investment Ltd.",Series F,20000000,NaN
1,12,2019-12-17,Healthians,B2B-focused foodtech startup,Food Solutions For Corporate,Bengaluru,"Paytm, NPTK, Sabre Partners and Neoplux",Series C,12000000,NaN
...,...,...,...,...,...,...,...,...,...,...
106,114,2019-02-08,Zilingo,Ecommerce,Fashion & Apparel,India/Singapore,"Sequoia Capital and Temasek Holdings, EDBI, Bu...",Series D,226000000,NaN
105,115,2019-02-13,NanoClean Global,Nanotechnology,Anti-Pollution,New Delhi,"LetsVenture, PitchRight Venture, 91SpringBoard...",Series A,600000,NaN
110,117,2019-01-03,CarDekho,Automobile,Online Marketplace,Jaipur,"Sequoia India, Hillhouse Capital, Alphabet\\xe...",Series C,110000000,NaN
108,118,2019-01-04,Vyome Therapeutics Inc.,Health and Wellness,Specialty pharmaceutical,India/US,"Iron Pillar, Perceptive Advisors, Romulus Capi...",Series D,22000000,NaN
109,119,2019-01-04,Samunnati Financial Intermediation & Services ...,Finance,Non-banking financial company,Chennai,"MASSIF, a Dutch government fund",Debt-Funding,5000000,NaN

In [54]:
df.reset_index(drop = True)

,Sr No,Date,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,8,2019-12-12,Ecozen,Technology,Agritech,Pune,Sathguru Catalyzer Advisors,Series A,6000000,NaN
1,9,2019-12-06,CarDekho,E-Commerce,Automobile,Gurgaon,Ping An Global Voyager Fund,Series D,70000000,NaN
2,10,2019-12-03,Dhruva Space,Aerospace,Satellite Communication,Bengaluru,"Mumbai Angels, Ravikanth Reddy",Seed,50000000,NaN
3,11,2019-12-13,Rivigo,Technology,Logistics Services and Solutions,Gurgaon,"SAIF Partners, Spring Canter Investment Ltd.",Series F,20000000,NaN
4,12,2019-12-17,Healthians,B2B-focused foodtech startup,Food Solutions For Corporate,Bengaluru,"Paytm, NPTK, Sabre Partners and Neoplux",Series C,12000000,NaN
...,...,...,...,...,...,...,...,...,...,...
106,114,2019-02-08,Zilingo,Ecommerce,Fashion & Apparel,India/Singapore,"Sequoia Capital and Temasek Holdings, EDBI, Bu...",Series D,226000000,NaN
107,115,2019-02-13,NanoClean Global,Nanotechnology,Anti-Pollution,New Delhi,"LetsVenture, PitchRight Venture, 91SpringBoard...",Series A,600000,NaN
108,117,2019-01-03,CarDekho,Automobile,Online Marketplace,Jaipur,"Sequoia India, Hillhouse Capital, Alphabet\\xe...",Series C,110000000,NaN
109,118,2019-01-04,Vyome Therapeutics Inc.,Health and Wellness,Specialty pharmaceutical,India/US,"Iron Pillar, Perceptive Advisors, Romulus Capi...",Series D,22000000,NaN
110,119,2019-01-04,Samunnati Financial Intermediation & Services ...,Finance,Non-banking financial company,Chennai,"MASSIF, a Dutch government fund",Debt-Funding,5000000,NaN

In [ ]:
#to manually give the name to the columns header. 

import pandas as pd

# Read the Excel file without treating the first row as headers
#df = pd.read_excel(r'C:\Users\Ali Muhtasham Javed\Downloads\indian_startup_funding_Lab1.xlsx', header = None, names=['A', 'B','C'])
#df.loc[0:112].. can be used to get data in tabular form.. 
#df

In [ ]:
#if only selected number of rows needs to be read

df = pd.read_excel(r'C:\Users\Ali Muhtasham Javed\Downloads\indian_startup_funding_Lab1.xlsx', header = 1, nrows = 2)
df_sorted = df.sort_values(by = 'Sr No', ascending=True). reset_index(drop= True)
print(df_sorted)
df[]

   Sr No       Date  Startup Name             Industry Vertical  \
0     12 2019-12-17    Healthians  B2B-focused foodtech startup
1     17 2019-12-20  Lenskart.com                    E-Commerce

                      SubVertical City  Location  \
0    Food Solutions For Corporate      Bengaluru
1  Online Eyewear Shopping Portal      Faridabad

                            Investors Name InvestmentnType  Amount in USD  \
0  Paytm, NPTK, Sabre Partners and Neoplux        Series C       12000000
1                     SoftBank Vision Fund        Series G      231000000

   Remarks
0      NaN
1      NaN